

about :

  name : wMathVector
  description : Collection of functions for vector math. MathVector introduces missing in JavaScript type VectorImage. VectorImage is a reference, it does not contain data but only refer on actual ( aka Long ) container of lined data. VectorImage could have offset, length and stride what makes look original container differently. Length of VectorImage is not necessarily equal to the length of the original container, siblings elements of VectorImage is not necessarily sibling in the original container, so storage format of vectors does not make a big difference for math algorithms. MathVector implements functions for the VectorImage and mirrors them for Array/Buffer. Use MathVector to be more functional with math and less constrained with storage format.
  version : 0.3.54
  enabled : 1
  interpreters :
  - nodejs >= 6.0.0
  - chrome >= 60.0.0
  - firefox >= 60.0.0
  keywords :
  - wTools

execution :

  scripts :
    test : wtest staging
    docgen : wdocgen staging

path :

  repository : git+https://github.com/Wandalen/wMathVector.git
  bugs : https://github.com/Wandalen/wMathVector/issues

build :

  debug.raw.export :
    exportDirPath : path::out.debug
    criterion :
      default : 1
      debug : 1
      raw : 1
      export : 1
      tar : 0
    steps :
      # - build::.debug.raw
      - step::export

  release.compiled.export :
    exportDirPath : path::out.release
    criterion :
      debug : 0
      raw : 0
      export : 1
      tar : 0
    steps :
      - build::release.compiled
      - step::export

  export.all :
    steps :
      - build::debug.raw.export
      - build::release.compiled.export

